const Constants = {
  ACTIVE_LAB_PDF: "ACTIVE_LAB_PDF",
  ACTIVE_DOC_PDF: "ACTIVE_DOC_PDF",
  AUTH_USER: "AUTH_USER",
  UNAUTH_USER: "UNAUTH_USER",
  AUTH_ERROR: "AUTH_ERROR",
  CLEAR_AUTH_ERROR: "CLEAR_AUTH_ERROR",
  LOGOUT_USER: "LOGOUT_USER",
  PAGE_ERROR: "PAGE_ERROR",
  PODS_ERROR: "PODS_ERROR",
  DOCS_ERROR: "PODS_ERROR",
  PODS_LOADING: "PODS_LOADING",
  DOCS_LOADING: "DOCS_LOADING",
  DEVICES_LOADING :"DEVICES_LOADING",
  DEVICES_ERROR :"DEVICES_ERROR"
}

export default Constants
